config/routes.rb
MaenadsApp::Application.routes.draw do

  root :to => "issues#home"
  get '/admins/login' => 'admins#login'
  post '/admins/login' => 'admins#admin_create'
  get '/admins/logout' => 'admins#logout'

  resources :admins

  resources :articles

  resources :issues

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  has_secure_password

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :article_date, :author, :body, :issue_id, :picture_link, :title

  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :issue_date, :number, :theme

  has_many :articles
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def login
    if session[:admin] == true
      redirect_to('/admins')
    end
  end

  def admin_create
    username = params[:username]
    password = params[:password]
    @admin = Admin.where(username: username).first
    if @admin && @admin.authenticate(password)
      session[:admin] = true
      redirect_to('/admins')
    else
      flash[:notice] = "Incorrect password"
      render :login
    end
  end

  def logout
    session[:admin] = false
    redirect_to('/')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
  def home
    @articles = Article.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create

  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/index.html.erb
<h1>Admin Home</h1>

<h2>Articles</h2>
<div class="link-list">
  <br>
  <a href="/articles/new">New Article</a>
  <br>
  <a href="/articles">Browse / Edit / Delete Articles</a>
</div>

<a href="/admins/logout">Log out of Admin</a>

app/views/admins/login.html.erb
<h2>Login as Admin</h2>
<%= form_tag('/admins/login') do %>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Login" %>
<% end %>
<div class="error">
  <%= flash[:notice] %>
</div>
<script>
  $('.error').fadeOut( 4000 );
</script>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture_link %><br />
    <%= f.text_field :picture_link %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br />
    <%= f.number_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :article_date %><br />
    <%= f.date_select :article_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
  <% if session[:admin] %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <style>
  th, td {
    padding: 15px;
    border: 1px solid black;
  }
  </style>

  <h1>Editing article</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
  <% end %>

  <script>
  var textarea = document.getElementById('article_body');
  var commandPressed = false;
  textarea.addEventListener("keydown", function(e) {
    if(e.keyCode === 9) {
      e.preventDefault();
      checkForHelpers(textarea);
    }
  });

  function getLastWord(s) {
    re = /\w+$/;
    var lastWord = s.match(re);
    return lastWord? lastWord[0] : '';
  }

  var keyWords = {
    img: "<img src='URL HERE'>",
    link: "<a href='URL HERE'> LINK TEXT HERE </a>",
    bold: "<span class='bold'> BOLD TEXT HERE </span>",
    italic: "<span class='italic'> ITALIC TEXT HERE </span>",
    title: "<span class='header'> HEADER-STYLE TEXT HERE </span>",
    p: "\n<p> NEW PARAGRAPH </p>"
  }

  function checkForHelpers(el) {
    var lastWord = getLastWord(el.value);
    if(keyWords.hasOwnProperty(lastWord)) {
      textarea.value = textarea.value.substring(0, textarea.value.lastIndexOf(' ')) + ' ' + keyWords[lastWord];
      // el.value += keyWords[lastWord];
    }
  }

  </script>

app/views/articles/index.html.erb
  <% if session[:admin] %>
  <!-- <link rel="stylesheet" href="/assets/scaffolds.css.scss"> -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<style>
  th, td {
    padding: 15px;
    border: 1px solid black;
  }
</style>
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Issue</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.author %></td>
    <td><%= article.issue_id %></td>
    <td><%= article.article_date %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>
  <% end %>

app/views/articles/new.html.erb
  <% if session[:admin] %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <style>
  th, td {
    padding: 15px;
    border: 1px solid black;
  }
  </style>
  <h1>New article</h1>

  <%= render 'form' %>

  <% end %>





  <script>
  var textarea = document.getElementById('article_body');
  var commandPressed = false;
  textarea.value = '<p>';
  textarea.addEventListener("keydown", function(e) {
    // Insert new paragraph on enter.
    if(e.keyCode === 13) {
      textarea.value += "</p> \n<p>";
      e.preventDefault();
      // shift b to create bold
    } else if(e.keyCode === 9) {
      e.preventDefault();
      checkForHelpers(textarea);
    }
  });

  function getLastWord(s) {
    re = /\w+$/;
    var lastWord = s.match(re);
    return lastWord? lastWord[0] : '';
  }

  var keyWords = {
    img: "<img src='URL HERE'>",
    link: "<a href='URL HERE'> LINK TEXT HERE </a>",
    bold: "<span class='bold'> BOLD TEXT HERE </span>",
    italic: "<span class='italic'> ITALIC TEXT HERE </span>",
    title: "<span class='header'> HEADER-STYLE TEXT HERE </span>"
  }

  function checkForHelpers(el) {
    var lastWord = getLastWord(el.value);
    if(keyWords.hasOwnProperty(lastWord)) {
      textarea.value = textarea.value.substring(0, textarea.value.lastIndexOf(' ')) + ' ' + keyWords[lastWord];
      // el.value += keyWords[lastWord];
    }
  }

  </script>

app/views/articles/show.html.erb
<link rel="stylesheet" href="../../assets/cube.css">


<div class="article-title"><%= @article.title %></div>
<div class="article-author"><%= @article.author %> <span class="article-date"> <%= @article.article_date %></span></div>

<div class="cube-container" style="position:relative;margin:0 auto;padding:40px;">
  <div class="cube toFront">
    <div class="face top"><%= image_tag @article.picture_link %></div>
    <div class="face front"><%= image_tag @article.picture_link %></div>
    <div class="face bottom"><%= image_tag @article.picture_link %></div>
    <div class="face left"><%= image_tag @article.picture_link %></div>
    <div class="face right"><%= image_tag @article.picture_link %></div>
    <div class="face rear"><%= image_tag @article.picture_link %></div>
  </div>
</div>

<div class="article-body">

  <%= @article.body.html_safe %>
</div>

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br />
    <%= f.date_select :issue_date %>
  </div>
  <div class="field">
    <%= f.label :theme %><br />
    <%= f.text_field :theme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
  <% if session[:admin] %>
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>
  <% end %>

app/views/issues/home.html.erb
<div class="nav">
  <div class="links">
    <% num = 1 %>
    <% @articles.sort.each do |article| %>
    <a href="/articles/<%= article.id %>"><%= num %></a>
    <% num += 1 %>
    <% end %>
  </div>
  <div class="title">
    <div class="glitch" data-text="MAENADS">
      MAENADS
    </div>
  </div>
</div>
<% num2 = 0 %>
<% @articles.each do |article| %>
<% directive = num2 % 2 == 0 ? "enter left" : "enter right" %>
  <div data-sr="<%= directive %>" class="image">
    <img src="<%= article.picture_link %>"   alt="">
  <div class="info-link">
    <span class="info-text">
      <a href="/articles/<%= article.id  %>"><%= article.title %> --></a>
    </span>
  </div>
</div>
<% num2 += 1 %>
<% end %>

app/views/issues/index.html.erb
  <% if session[:admin] %>
<h1>Listing issues</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Issue date</th>
    <th>Theme</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.number %></td>
    <td><%= issue.issue_date %></td>
    <td><%= issue.theme %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>
  <% end %>

app/views/issues/new.html.erb
  <% if session[:admin] %>
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>
  <% end %>

app/views/issues/show.html.erb
  <% if session[:admin] %>
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @issue.number %>
</p>

<p>
  <b>Issue date:</b>
  <%= @issue.issue_date %>
</p>

<p>
  <b>Theme:</b>
  <%= @issue.theme %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MaenadsApp</title>
  <link rel="stylesheet" href="/assets/reset.css">
  <!-- <link rel="stylesheet" href="/assets/main.css"> -->
  <link rel="stylesheet" href="/assets/style.css">
  <link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="/assets/glitch.css">
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/tah0tlt.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
  <script>

  window.sr = new scrollReveal({
    reset: true
  });

  </script>
</body>
</html>